
CREATE TABLE emails (id serial PRIMARY KEY, sender text, recipient text, subject text, message text, date timestamp);
INSERT INTO emails (sender, recipient, subject, message, date) VALUES  
( 'katie@galvanize.com', 'jane@galvanize.com' ,  'Standup meeting',  'Mr. and Mrs. Dursley, of number four, Privet Drive, wereproud to say that they were perfectly normal, thankyou very much.' ,  '2020-08-23T18:25:43.511Z'),
( 'katie@galvanize.com', 'jane@galvanize.com' ,  'Standup meeting',  'Mr. and Mrs. Dursley, of number four, Privet Drive, wereproud to say that they were perfectly normal, thankyou very much.' ,  '2020-08-23T18:25:43.511Z'),
( 'jean-marc@galvanize.com', 'jane@galvanize.com' ,  'Retro meeting',  'They were the last people you’d expect to be involved in anything strange or mysterious, because they just didn’thold with such nonsense.',  '2020-04-23T18:25:43.511Z'),
( 'ash@galvanize.com', 'jane@galvanize.com',  'New employee next week',  'Mr. Dursley was the director of a fi rm called Grunnings, whichmade drills. He was a big, beefy man with hardly any neck, although he did have a very large mustache. ',  '2019-01-23T18:25:43.511Z'),
( 'mattias@galvanize.com', 'jane@galvanize.com',  'Last week''s reports',  ' Mrs. Dursley was thin and blonde and had nearly twice the usual amount of neck, which came in very useful as she spent so much of her time craning over garden fences, spying on the neighbors.',  '2020-06-23T18:25:43.511Z'),
( 'tanner@galvanize.com', 'jane@galvanize.com',  'Holiday schedule',  'The Dursleys had a small son called Dudley and in their opinion there was no finer boy anywhere.',  '2020-03-23T18:25:43.511Z'),
( 'brandon@galvanize.com', 'jane@galvanize.com',  'Managers meeting',  'The Dursleys had everything they wanted, but they also had a secret, and their greatest fear was that somebody would discover it. ',  '2020-02-23T18:25:43.511Z'),
( 'jeff@galvanize.com', 'jane@galvanize.com',  '1 on 1 meeting',  ' ey didn’t think they could bear it if anyone found out about thePotters. ',  '2020-02-23T18:25:43.511Z'),
( 'maddie@galvanize.com', 'jane@galvanize.com',  'Happy hour next Friday!' , ' Mrs. Potter was Mrs. Dursley’s sister, but they hadn’t met for several years; in fact, Mrs. Dursley pretended she didn’t have a sister' ,  '2019-12-23T18:25:43.511Z'),
( 'becky@galvanize.com', 'jane@galvanize.com',  'Vacation Request',  '  e Dursleys shudderedto think what the neighbors would say if the Potters arrived in the street.',  '2020-01-23T18:25:43.511Z'),
( 'jarret@galvanize.com', 'jane@galvanize.com',  'All hands meeting',  ' is boy was another good reason for keeping the Potters away; they didn’t want Dudley mixing with a child like that.',  '2019-07-23T18:25:43.511Z'),
( 'rich@galvanize.com', 'jane@galvanize.com',  'Standup meeting',  '  e Dursleys knew that the Potters had a small son, too, butthey had never even seen him.',  '2020-03-23T18:25:43.511Z'),
( 'erin@galvanize.com', 'jane@galvanize.com',  'New hire orientation assistance needed',  'When Mr. and Mrs. Dursley woke up on the dull, gray Tuesday our story starts, there was nothing about the cloudy sky outside tosuggest that strange and mysterious things would soon be happening all over the country',  '2020-04-23T18:25:43.511Z'),
( 'charlie@galvanize.com', 'jane@galvanize.com',  'Expense reports due!',  ' Mr. Dursley hummed as he picked out his most boring tie for work, and Mrs. Dursley gossiped away happily as she wrestled a screaming Dudley into his high chair.',  '2018-05-23T18:25:43.511Z'),
( 'jacob@galvanize.com', 'jane@galvanize.com',  'Updated travel policy information',  'None of them noticed a large, tawny owl fl utter past the window',   '2018-05-23T18:25:43.511Z'),
( 'louise@galvanize.com', 'jane@galvanize.com',  'Cat videos',  'At half past eight, Mr. Dursley picked up his briefcase, pecked  Mrs. Dursley on the cheek, and tried to kiss Dudley good-bye but missed, because Dudley was now having a tantrum and throwing his cereal at the walls. ',  '2020-02-23T18:25:43.511Z'),
( 'ash@galavnize.com', 'jane@galvanize.com',  'I need help',  ' “Little tyke,” chortled Mr. Dursley as he left  the house. ',  '2019-04-23T18:25:43.511Z'),
( 'ash@galvanize.com', 'jane@galvanize.com',  'Blocked on React issue',  'He got into his car and backed out of number four’s drive',  '2020-03-23T18:25:43.511Z'),
( 'katie@galvanize.com', 'jane@galvanize.com',  'Happy hour this Thursday!',  'It was on the corner of the street that he noticed the fi rst sign of something peculiar — a cat reading a map',   '2020-03-23T18:25:43.511Z'),
( 'brandon@galvanize.com', 'jane@galvanize.com',  'Standup Notes',  'For a second, Mr.  Dursley didn’t realize what he had seen — then he jerked his head  around to look again.',  '2020-03-23T18:25:43.511Z');